### ISSUE TITLE
Can't install on remnote 1.8.68 MAC

### ISSUE THREAD

**Issue by Saadchr** [bjsi/remnote-readwise#1]
I can't install the new readwise plugin by clicking on "Install"
Remnote desktop 1.868 MAC OS Ventura 13.01

I have those 2 power up installed  (I think coming from the previous plugin) that I can't remove: 
Readwise Book
Readwise Highlight
Could that be the reason I can't install the plugin?

**Comment by bjsi** [comment]
It should work when your remnote updates to 1.8.69

**Comment by bjsi** [comment]
@Saadchr Is it working for you now?

**Comment by Saadchr** [comment]
@bjsi Thanks, It is working now!
