### ISSUE TITLE
Articles are being duplicated

### ISSUE THREAD

**Issue by britannio** [bjsi/remnote-readwise#11]
When I revisit a note and add new highlights to it, a new document rem with the same title is created.

This might be an underlying issue with how Readwise works as it is creating a separate book review URL that only contains the new highlights.

**Comment by yun-kwak** [comment]
It appears that the Readwise plugin is creating a highlight article for each device (e.g. macOS, Web, iOS). This leads to the creation of duplicate articles in RemNote for the same content if multiple devices are being used simultaneously.

**Comment by bjsi** [comment]
I added some code recently to wait for the initial remnote sync before doing its own syncing. I think this should resolve the issue, but please let me know if it reoccurs.
