### ISSUE TITLE
Failed import

### ISSUE THREAD

**Issue by gresham-1** [bjsi/remnote-readwise#2]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/122383865/211599713-5aea9b5d-80d5-40d6-9bde-5d5743a992f5.png">

**Comment by bjsi** [comment]
@gresham-1 what version of RemNote are you on? This plugin requires some features which were only added in 1.8.69

**Comment by bjsi** [comment]
@gresham-1 I updated the plugin and added verbose error messages, so if you rerun it should tell us why it failed.

**Comment by gresham-1** [comment]
I’ll check one sec

Gresham, Sean
Biological sciences C/O 2023
Boonshoft SOM C/O 2027
Marine veteran
[X]
________________________________

**Comment by gresham-1** [comment]
It works! Is there a way to also get my notes pulled?

Gresham, Sean
Biological sciences C/O 2023
Boonshoft SOM C/O 2027
Marine veteran
[X]
________________________________

**Comment by bjsi** [comment]
@gresham-1 Oh I didn't realise highlights could have notes. I could add that :+1:
