### ISSUE TITLE
Endless loop: Can no longer use remnote

### ISSUE THREAD

**Issue by Saadchr** [bjsi/remnote-readwise#4]
I have those 2 windows poping up endlessely preventing me from using Remnote
MAC OS Ventura 13.01
Desktop Remnote 1.869
<img width="426" alt="CleanShot 2023-01-12 at 13 53 40@2x" src="https://user-images.githubusercontent.com/74289775/212071474-c0484f2e-9d9f-4198-9240-77699892128f.png">
<img width="497" alt="CleanShot 2023-01-12 at 13 53 50@2x" src="https://user-images.githubusercontent.com/74289775/212071535-c2d7b642-4477-4adf-a141-b9029a509feb.png">

**Comment by bjsi** [comment]
Is this still happening? Did you run any commands or did it suddenly start
happening?

**Comment by Saadchr** [comment]
Yes it's still happening. It all started by adding a note on a highlight in Readwise.
On Chrome and Mobile, The whole rem about this highlight no longer appears on Readwise Books, but I can use remnote.
On desktop, I can no longer use the app.

**Comment by bjsi** [comment]
I made some fixes to the plugin. The window popup should be fixed. The database error issue should also be fixed. For the spinner issue, do you mind sending a message to support through the app? I will message Martin to take a look ASAP
