### ISSUE TITLE
[BUG] I ended up with 2 documents " Readwise Books"

### ISSUE THREAD

**Issue by Saadchr** [bjsi/remnote-readwise#5]
I have now two  separate documents with the name "Readwise Books". The latter syncing the notes with the highlights.
How can I merge them while having the sync working properly?

**Comment by bjsi** [comment]
Did you move the Readwise Books document after importing?

**Comment by Saadchr** [comment]
I deleted both documents and children rem, uninstall the plugin, reinstall it and synced all again.
It works now
